name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAMESPACE: ciasun

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build & Run Tests
      run: |
        dotnet build --configuration Release --no-restore
        dotnet test --no-build --verbosity normal

    - name: Log in to Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Users API image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: src/Services/UserService/RSpot.Users.API/Dockerfile
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/rspot-users:latest

    - name: Build and push Places API image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: src/Services/PlaceService/RSpot.Places.API/Dockerfile
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/rspot-places:latest

    - name: Build and push Booking API image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: src/Services/BookingService/RSpot.Booking.API/Dockerfile
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/rspot-booking:latest

    - name: Build and push Notification Worker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: src/Services/NotificationService/RSpot.NotificationService/Dockerfile
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/rspot-notification:latest
